-- sofia_ruleta.mercado_premio definition

CREATE TABLE `mercado_premio` (
  `ID_MERCADO_PREMIO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_MERCADO` int(11) DEFAULT NULL,
  `ID_PREMIO` int(11) DEFAULT NULL,
  `CANTIDAD_MAX_SALIDAS` int(8) DEFAULT NULL,
  `CANTIDAD_ENTREGADO_DIARIO` int(8) DEFAULT NULL,
  `PREMIO_CONSUELO` varchar(2) DEFAULT NULL,
  `USER_CREACION` varchar(150) CHARACTER SET utf8 COLLATE utf8_spanish2_ci DEFAULT NULL,
  `FECHA_CREACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_MERCADO_PREMIO`),
  KEY `ID_MERCADO` (`ID_MERCADO`),
  KEY `ID_PREMIO` (`ID_PREMIO`),
  CONSTRAINT `ID_MERCADO` FOREIGN KEY (`ID_MERCADO`) REFERENCES `mercado` (`ID_MERCADO`),
  CONSTRAINT `ID_PREMIO` FOREIGN KEY (`ID_PREMIO`) REFERENCES `premio` (`ID_PREMIO`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;

-- Datos
insert
	into
	sofia_ruleta.mercado_premio (ID_MERCADO,
	ID_PREMIO,
	CANTIDAD_MAX_SALIDAS,
	CANTIDAD_ENTREGADO_DIARIO,
	USER_CREACION,
	FECHA_CREACION)
values
	 (3,1,3,3,'admin','2023-05-09 12:26:33'),
	 (3,2,5,6,'admin','2023-05-09 12:28:01'),
	 (3,3,5,7,'admin','2023-05-09 12:28:37'),
	 (3,4,8,0,'admin','2023-05-09 12:29:50'),
	 (3,5,0,0,'admin','2023-05-19 21:31:26');