-- sofia_ruleta.cliente_premiado definition

CREATE TABLE `CLIENTE_PREMIADO` (
  `ID_CLIENTE_PREMIEADO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRES` varchar(100) CHARACTER SET utf8 COLLATE utf8_spanish2_ci DEFAULT NULL,
  `APELLIDOS` varchar(150) CHARACTER SET utf8 COLLATE utf8_spanish2_ci DEFAULT NULL,
  `CARNET_IDENTIDAD` varchar(100) CHARACTER SET utf8 COLLATE utf8_spanish2_ci DEFAULT NULL,
  `TELEFONO` varchar(20) CHARACTER SET utf8 COLLATE utf8_spanish2_ci DEFAULT NULL,
  `ID_CIUDAD` int(11) DEFAULT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `NRO_TICKET` varchar(150) CHARACTER SET utf8 COLLATE utf8_spanish2_ci DEFAULT NULL,
  `ESTADO` varchar(1) DEFAULT NULL,
  `ID_MERCADO` int(11) DEFAULT NULL,
  `ID_PREMIO` int(11) DEFAULT NULL,
  `USER_CREACION` varchar(150) DEFAULT NULL,
  `FECHA_CREACION` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE_PREMIEADO`),
  KEY `ID_PREMIO1` (`ID_MERCADO`),
  KEY `ID_CIUDAD` (`ID_CIUDAD`),
  CONSTRAINT `ID_CIUDAD` FOREIGN KEY (`ID_CIUDAD`) REFERENCES `CIUDAD` (`ID_CIUDAD`),
  CONSTRAINT `ID_MERCADO1` FOREIGN KEY (`ID_MERCADO`) REFERENCES `MERCADO` (`ID_MERCADO`),
  CONSTRAINT `ID_PREMIO1` FOREIGN KEY (`ID_MERCADO`) REFERENCES `PREMIO` (`ID_PREMIO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
